name:MYCI
on:
  push:
  branches:
  - master
  paths:
  - src/*
jobs:
  job1:
     runs-on:ubuntu-latest
     container:
     image: node:8
     steps:
     - uses:active/checkout@v1
     - run: |
         node -v
